version: 2

sources:
  - name: raw_data
    description: "Raw source data from CSV of video game sales"
    tables:
      - name: databefore
        description: "Raw video game sales data"

models:
  - name: Dim_Game
    description: "Unique list of games"
    columns:
      - name: game_id
        tests: [unique, not_null]
      - name: game_name
        tests: [not_null]

  - name: Dim_Platform
    description: "Unique list of platforms"
    columns:
      - name: platform_id
        tests: [unique, not_null]
      - name: platform_name
        tests: [not_null]

  - name: Dim_Year
    description: "Unique list of years"
    columns:
      - name: year_id
        tests: [unique, not_null]
      - name: year
        tests: [not_null]

  - name: Dim_Genre
    description: "Unique list of genres"
    columns:
      - name: genre_id
        tests: [unique, not_null]
      - name: genre_name
        tests: [not_null]

  - name: Dim_Publisher
    description: "Unique list of publishers"
    columns:
      - name: publisher_id
        tests: [unique, not_null]
      - name: publisher_name
        tests: [not_null]

  - name: Fact_Sales
    description: "Fact table containing sales by game, platform, year, genre, publisher"
    columns:
      - name: sales_id
        tests: [unique, not_null]
      - name: game_id
        tests: [not_null]
      - name: platform_id
        tests: [not_null]
      - name: year_id
        tests: [not_null]
      - name: genre_id
        tests: [not_null]
      - name: publisher_id
        tests: [not_null]
