project_snowflake:
  outputs:
    dev:
      account: RNJTPPB-JHB70739
      database: FINALPROJECT
      password: ******************
      role: ACCOUNTADMIN
      schema: RAW
      threads: 4
      type: snowflake
      user: MOSTAFAMOHAMED
      warehouse: COMPUTE_WH

  target: dev
