project_snowflake:
  outputs:
    dev:
      account: 
      database: FINALPROJECT
      password: 
      role: ACCOUNTADMIN
      schema: RAW
      threads: 4
      type: snowflake
      user: 
      warehouse: COMPUTE_WH

  target: dev

